version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '83:80'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
  frontend:
    build: ./frontend
    ports:
      - '3003:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
